# Generated by Django 2.0.1 on 2018-01-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.IntegerField(blank=True, choices=[(1, 'Духовка'), (2, 'Гриль')])),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.IntegerField(blank=True, choices=[(1, 'ПП'), (2, 'Вегетарианские')])),
            ],
        ),
        migrations.CreateModel(
            name='CategoryGeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.IntegerField(blank=True, choices=[(1, 'Европейская'), (2, 'Азиатская')])),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.IntegerField(blank=True, choices=[(1, 'Вторые блюда'), (2, 'Салаты')])),
            ],
        ),
        migrations.CreateModel(
            name='CategoryUsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.IntegerField(blank=True, choices=[(1, 'На обед'), (2, 'На завтрак')])),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('count', models.IntegerField(blank=True, default=1)),
                ('measure', models.IntegerField(blank=True, choices=[(1, 'Кг'), (2, 'Граммы')])),
                ('ingr_descr', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(blank=True, max_length=200)),
                ('shortdescription', models.CharField(blank=True, max_length=200)),
                ('youtube', models.CharField(blank=True, help_text='Вставьте ссылку на видео с YouTube, если она имеется', max_length=200)),
                ('time', models.CharField(blank=True, max_length=200)),
                ('measure', models.IntegerField(choices=[(1, 'Минуты'), (2, 'Часы')], default=1)),
                ('alldescr', models.CharField(blank=True, max_length=200)),
                ('count', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='files/')),
                ('category_cooking', models.ManyToManyField(blank=True, to='cookbook.CategoryCooking')),
                ('category_diet', models.ManyToManyField(blank=True, to='cookbook.CategoryDiet')),
                ('category_geo', models.ManyToManyField(blank=True, to='cookbook.CategoryGeo')),
                ('category_main', models.ManyToManyField(blank=True, to='cookbook.CategoryMain')),
                ('category_using', models.ManyToManyField(blank=True, to='cookbook.CategoryUsing')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recipe'),
        ),
        migrations.AddField(
            model_name='alldescription',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recipe'),
        ),
    ]
