# Generated by Django 2.0.1 on 2018-01-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryusing',
            name='options',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
