# Generated by Django 2.0.1 on 2018-01-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20180117_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='alldescr',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
