# Generated by Django 2.0.1 on 2018-01-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20180118_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldescription',
            name='photo',
            field=models.ImageField(blank=True, upload_to='files/'),
        ),
    ]
