# Generated by Django 2.0.1 on 2018-01-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_auto_20180118_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='measure',
            field=models.CharField(blank=True, choices=[(1, 'Минуты'), (2, 'Часы')], max_length=200),
        ),
    ]
