# Generated by Django 2.0.1 on 2018-02-02 08:30

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('cookbook', '0011_auto_20180201_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientbase',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredientbase',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
