# Generated by Django 2.0.1 on 2018-02-02 19:00

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('cookbook', '0012_auto_20180202_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeSearchForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(blank=True, max_length=200, verbose_name='Название рецепта')),
                ('category_cooking', models.ManyToManyField(blank=True, to='cookbook.CategoryCooking')),
                ('category_diet', models.ManyToManyField(blank=True, to='cookbook.CategoryDiet')),
                ('category_geo', models.ManyToManyField(blank=True, to='cookbook.CategoryGeo')),
                ('category_main', models.ManyToManyField(blank=True, to='cookbook.CategoryMain')),
                ('category_using', models.ManyToManyField(blank=True, to='cookbook.CategoryUsing')),
                ('ingredients', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.',
                                                                through='taggit.TaggedItem', to='taggit.Tag',
                                                                verbose_name='Tags')),
            ],
        ),
    ]
