# Generated by Django 2.0.1 on 2018-02-05 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('cookbook', '0013_recipesearchform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeSearchForm',
            new_name='RecipeSearchModel',
        ),
    ]
