# Generated by Django 2.0.1 on 2018-02-05 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cookbook', '0014_auto_20180205_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesearchmodel',
            name='category_cooking',
        ),
        migrations.RemoveField(
            model_name='recipesearchmodel',
            name='category_diet',
        ),
        migrations.RemoveField(
            model_name='recipesearchmodel',
            name='category_geo',
        ),
        migrations.RemoveField(
            model_name='recipesearchmodel',
            name='category_main',
        ),
        migrations.RemoveField(
            model_name='recipesearchmodel',
            name='category_using',
        ),
        migrations.RemoveField(
            model_name='recipesearchmodel',
            name='recipe_name',
        ),
    ]
