# Generated by Django 2.0.1 on 2018-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cookbook', '0015_auto_20180205_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesearchmodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ингредиент'),
        ),
    ]
