# Generated by Django 2.0.1 on 2018-02-05 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cookbook', '0016_recipesearchmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesearchmodel',
            name='name',
        ),
    ]
