# Generated by Django 2.0.1 on 2018-02-05 14:55

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ('cookbook', '0018_auto_20180205_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientbase',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
