"""
Constants for application
"""
USER_NAME = "Имя"
USER_NAME_HELP_TEXT = "Ваше имя. Заполнять не обязательно."
LAST_NAME = "Фамилия"
LAST_NAME_HELP_TEXT = "Ваша фамилия. Заполнять не обязательно."
PASSWD1 = "Пароль"
PASSWD1_HELP_TEXT = "Введите пароль."
PASSWD2 = "Введите пароль еще раз"
PASSWD2_HELP_TEXT = "Введите пароль еще раз."
VALIDATION_ERROR = "Пароли не совпадают"

EMAIL_LABEL = "Электронная почта"
EMAIL_HELP_TEXT = "Существующий адрес электронной почты. Все почтовые сообщения с сайта будут отсылаться на этот адрес."
LOGIN_ERROR = "Пользователь не существует"
REGISTER_ERROR = "Ошибка создания пользователя"
